apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agderfk-no

resources:
  - ../../../base

commonLabels:
  fintlabs.no/org-id: agderfk.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-resource-gateway_agderfk_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "agderfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "agderfk.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "https://beta.felleskomponent.no"
    target:
      kind: Application
      name: fint-resource-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_agderfk_no"
      - op: replace
        path: "/spec/orgId"
        value: "agderfk.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client

