apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: fint-resource-gateway
  name: fint-resource-gateway
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: fint-resource-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    operator.1password.io/item-path: "vaults/aks-alpha-vault/items/skjema-resource-gateway"
    operator.1password.io/item-name: "skjema-resource-gateway"
  labels:
    io.kompose.service: fint-resource-gateway
  name: fint-resource-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-resource-gateway
  template:
    metadata:
      labels:
        io.kompose.service: fint-resource-gateway
    spec:
      restartPolicy: Always
      containers:
        #- image: fintlabsacr.azurecr.io/fint-resource-gateway:build.${BUILD_NUMBER}_${GIT_COMMIT}
        - image: fintlabsacr.azurecr.io/fint-resource-gateway:build.12_005ca14e0a23fb67d66d5cab0cf8742e8dfd699b
          name: fint-resource-gateway
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: "skjema-resource-gateway"
          env:
            - {name: TZ, value: Europe/Oslo}
            #- {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx480M -verbose:gc'}
            - {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx920M'}
            - {name: spring.kafka.consumer.bootstrap-servers, value: 'kafka-0.kafka-headless.default.svc.cluster.local:9092'}
            - {name: spring.kafka.producer.bootstrap-servers, value: 'kafka-0.kafka-headless.default.svc.cluster.local:9092'}
            - {name: spring.kafka.bootstrap-servers, value: 'kafka-0.kafka-headless.default.svc.cluster.local:9092'}
            - {name: logging.level.no.fintlabs.arkiv, value: info}
            - {name: logging.level.no.fintlabs.kafka, value: info}