fint:
  client:
    registration-id: fint
    username: ${fint.core.oauth2.username}
    password: ${fint.core.oauth2.password}
spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            provider: fint-idp
            scope: fint-client
            client-id: ${fint.core.oauth2.client-id}
            client-secret: ${fint.core.oauth2.client-secret}