fint:
  org-id: fintlabs.no
  client:
    password: ''
    username: ''
    base-url: https://beta.felleskomponent.no
    registration-id: fint
  kodeverk:
    resources:
      resend:
        cron: 0 0 0 */6 * *
      polling:
        initialDelay: 5000
        fixedDelay: 900000
      entityPipelines:
        - resourceReference: arkiv.noark.administrativenhet
        - resourceReference: arkiv.noark.klassifikasjonssystem
        - resourceReference: arkiv.kodeverk.rolle
        - resourceReference: arkiv.kodeverk.saksstatus
        - resourceReference: arkiv.noark.arkivdel
        - resourceReference: arkiv.kodeverk.skjermingshjemmel
        - resourceReference: arkiv.kodeverk.tilgangsrestriksjon
        - resourceReference: arkiv.kodeverk.klassifikasjonstype
        #- resourceReference: arkiv.noark.klasse
        - resourceReference: arkiv.kodeverk.dokumentstatus
        - resourceReference: arkiv.kodeverk.dokumenttype
        - resourceReference: arkiv.noark.arkivressurs
        - resourceReference: administrasjon.personal.personalressurs
          selfLinkKeyFilter: ansattnummer
        - resourceReference: administrasjon.personal.person
          selfLinkKeyFilter: fodselsnummer
spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-client
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: group_id
logging:
  level:
    org.apache.kafka: ERROR
    no.fintlabs.kafka.consumer.cache: WARN