fint:
  application-id: fint-resource-gateway
  flyt:
    resource-gateway:
      resources:
        refresh:
          interval-ms: 518400000
          topic-retention-time-offset-ms: 86400000
        pull:
          initial-delay-ms: 5000
          fixed-delay-ms: 900000
        entity-pipelines:
          - resource-reference: arkiv.noark.administrativenhet
          - resource-reference: arkiv.noark.klassifikasjonssystem
            sub-entity-pipeline-configuration:
              reference: klasse
              key-suffix-filter: klasseId
          - resource-reference: arkiv.kodeverk.rolle
          - resource-reference: arkiv.kodeverk.partrolle
          - resource-reference: arkiv.kodeverk.korrespondanseparttype
          - resource-reference: arkiv.kodeverk.saksstatus
          - resource-reference: arkiv.noark.arkivdel
          - resource-reference: arkiv.kodeverk.skjermingshjemmel
          - resource-reference: arkiv.kodeverk.tilgangsrestriksjon
          - resource-reference: arkiv.kodeverk.klassifikasjonstype
          - resource-reference: arkiv.kodeverk.dokumentstatus
          - resource-reference: arkiv.kodeverk.dokumenttype
          - resource-reference: arkiv.kodeverk.journalposttype
          - resource-reference: arkiv.kodeverk.journalstatus
          - resource-reference: arkiv.kodeverk.variantformat
          - resource-reference: arkiv.kodeverk.format
          - resource-reference: arkiv.kodeverk.saksmappetype
          - resource-reference: arkiv.noark.arkivressurs
          - resource-reference: administrasjon.personal.personalressurs
            self-link-key-filter: ansattnummer
          - resource-reference: administrasjon.personal.person
            self-link-key-filter: fodselsnummer
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - flyt-fint-client
