fint:
  org-id: fintlabs.no
  resource-gateway:
    authorization:
      enable: true
  client:
    base-url: http://localhost:3000
    #base-url: https://beta.felleskomponent.no
  kafka:
    default-replicas: 1
spring:
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8089