fint:
  org-id: fintlabs.no
  client:
    password: ''
    username: ''
    base-url: https://beta.felleskomponent.no
    registration-id: fint
  kafka:
    application-id: fint-resource-gateway
  flyt:
    resource-gateway:
      resources:
        refresh:
          interval-ms: 518400000
          topic-retention-time-offset-ms: 86400000
        pull:
          initial-delay-ms: 5000
          fixed-delay-ms: 900000
        entity-pipelines:
          - resource-reference: arkiv.noark.administrativenhet
          - resource-reference: arkiv.noark.klassifikasjonssystem
          - resource-reference: arkiv.kodeverk.rolle
          - resource-reference: arkiv.kodeverk.saksstatus
          - resource-reference: arkiv.noark.arkivdel
          - resource-reference: arkiv.kodeverk.skjermingshjemmel
          - resource-reference: arkiv.kodeverk.tilgangsrestriksjon
          - resource-reference: arkiv.kodeverk.klassifikasjonstype
          - resource-reference: arkiv.kodeverk.dokumentstatus
          - resource-reference: arkiv.kodeverk.dokumenttype
          - resource-reference: arkiv.kodeverk.journalstatus
          - resource-reference: arkiv.kodeverk.variantformat
          - resource-reference: arkiv.noark.arkivressurs
          - resource-reference: administrasjon.personal.personalressurs
            self-link-key-filter: ansattnummer
          - resource-reference: administrasjon.personal.person
            self-link-key-filter: fodselsnummer
spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-client
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-resource-gateway
logging:
  level:
    root: INFO
    org.apache.kafka: INFO