apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: innlandetfylke-no

resources:
  - ../../../base

commonLabels:
  fintlabs.no/org-id: innlandetfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-resource-gateway_innlandetfylke_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "innlandetfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "innlandetfylke.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "https://api.felleskomponent.no"
    target:
      kind: Application
      name: fint-resource-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_innlandetfylke_no"
      - op: replace
        path: "/spec/orgId"
        value: "innlandetfylke.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client
