apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-resource-gateway
data:
  TZ: 'Europe/Oslo'
  JAVA_TOOL_OPTIONS: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
  fint.org-id: 'vlfk.no'
  fint.client.base-url: 'https://beta.felleskomponent.no'
  fint.flyt.resource-gateway.authorization.enable: 'true'
  logging.level.no.fintlabs.arkiv: 'info'
  logging.level.no.fintlabs.kafka: 'info'