apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: viken-no-fint-resource-gateway
spec:
  itemPath: "vaults/aks-alpha-vault/items/vlfk-no-flyt-fint-resource-gateway"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-resource-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: fint-resource-gateway-kafka-certificates
      containers:
        - image: ghcr.io/fintlabs/fint-resource-gateway:sha-0000000
          name: fint-resource-gateway
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "4Gi"
              cpu: "1"
            requests:
              memory: "4Gi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: fint-resource-gateway-kafka
            - secretRef:
                name: viken-no-fint-resource-gateway
            - configMapRef:
                name: fint-resource-gateway