apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-resource-gateway
  namespace: fintlabs-no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-resource-gateway:sha-0000000
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
  envFrom:
    - secretRef:
        name: fint-resource-gateway-fint-client
  resources:
    limits:
      memory: "4Gi"
      cpu: "1"
    requests:
      memory: "4Gi"
      cpu: "100m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }