apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfylke-no

resources:
  - ../../../base2

commonLabels:
  fintlabs.no/org-id: trondelagfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-resource-gateway_trondelagfylke_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "trondelagfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "https://api.felleskomponent.no"
    target:
      kind: Application
      name: fint-resource-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-egrunnerverv-fint-client_trondelagfylke_no"
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
    target:
      kind: FintClient
      name: fint-flyt-egrv-fint-client
